Leaving out the time of expense date when filtering
LiteFarmOrg/LiteFarm pull request #1716
Opened 2021-12-14 11:09 UTC by hernandcb

2021-12-15 15:40 UTC, smattingly requested changes
I believe this fixes the problem in the Summary table of the Other Expenses screen, but not the Detailed History on that screen. I think the same problem exists with Labour costs, and possibly also with Revenue. So, I think a similar fix is needed in other places.

2021-12-15 15:40 UTC, smattingly commented on packages/webapp/src/containers/Finances/OtherExpense/index.js
> +        moment(expenseDate).utc().isSameOrAfter(moment(startDate)) &&
Line 83 ensures `expenseDate` is a `moment`, so I think there's no need to call `moment()` on `expenseDate` here, or on the next line.

2021-12-15 20:50 UTC, hernandcb commented
I changed the way to remove the time on the dates and also applied the same changes to all the other filters.

2021-12-21 12:19 UTC, hernandcb commented
Thank you for the suggestions. Indeed, it is more clearer and cleaner in that way. 
Sorry I didn't check that out in the library before.

2022-01-01 02:38 UTC, smattingly requested changes
Requesting one small change ...

2022-01-01 02:38 UTC, smattingly commented on packages/webapp/src/containers/Finances/index.js
> +    console.log('///////// Entrando')
Please remove this.

2022-01-12 09:52 UTC, hernandcb commented on packages/webapp/src/containers/Finances/index.js
> +    console.log('///////// Entrando')
Done

2022-01-12 15:59 UTC, smattingly reviewed
:+1:

2022-01-12 16:01 UTC, smattingly approved these changes

2022-01-12 16:02 UTC, merged