[ST-388]  Adding crop's name on "Actual Revenue"
LiteFarmOrg/LiteFarm pull request #1721
Opened 2021-12-16 16:51 UTC by hernandcb

Added the name of the crop as complement to the Crop variety name in the Actual revenue page.
I used the same pattern used in the estimated crop revenue.

2021-12-18 20:22 UTC, smattingly requested changes
You've put together the proper string, but haven't made it display.

2021-12-18 20:22 UTC, smattingly commented on packages/webapp/src/containers/Finances/ActualCropRevenue/index.js
> +        const title = cropVariety.crop_variety_name
The value of `title` is never used. You need to use it in the returned object.

2021-12-21 10:11 UTC, hernandcb commented
Oh, I don't know why I sent it like that. Fixed it, also added the key prop to avoid a React warning that was appearing.

2021-12-30 05:54 UTC, JimmyRowland commented
Couldn't push onto this branch. Moved this pr here https://github.com/LiteFarmOrg/LiteFarm/pull/1733

2021-12-30 05:54 UTC, closed without merging