2180/vite to merge
LiteFarmOrg/LiteFarm pull request #1806
Opened 2022-02-09 07:40 UTC by JimmyRowland

2022-02-09 19:40 UTC, smattingly requested changes
With npm's start script removed, I wasn't sure how to proceed. Please update the README with any new/changed instructions. Launched with vite script but hit this when I started typing address to create a farm:
![image](https://user-images.githubusercontent.com/21227171/153277433-6943da88-309b-44d5-bbd1-8fe8f9d618aa.png)

2022-02-10 16:08 UTC, smattingly requested changes

2022-02-10 17:35 UTC, JimmyRowland commented on README.md
> +3. In a terminal, run `npm i` under the root folder of the repository, `npm i` under `packages/api`, and `pnpm i`
it's good enough for now. Added a new ticket to resolve package manager confusions.
[LF-2234]

2022-02-10 18:54 UTC, smattingly commented on README.md
> +3. In a terminal, run `npm i` under the root folder of the repository, `npm i` under `packages/api`, and `pnpm i`
I will probably be responsible for automating deployment of this. I disagree that it's good enough for now.

2022-02-11 15:43 UTC, smattingly commented on README.md
> +3. In a terminal, run `npm i` under the root folder of the repository, `npm i` under `packages/api`, and `pnpm i`
I made further comments on the Jira ticket requesting changes in dependency management.

2022-02-11 15:51 UTC, smattingly requested changes

2022-02-11 15:51 UTC, smattingly commented on README.md
> +3. In a terminal, run `npm i pnpm -g` *if pnpm is not already installed*, run `npm i` under the root folder of the
To ease automation, please put all dependencies in package.json or equivalent (https://12factor.net/dependencies). Please avoid global installs if not necessary.

2022-02-12 00:36 UTC, merged