LF-2376/notify user when task reassigned to someone else
LiteFarmOrg/LiteFarm pull request #1885
Opened 2022-05-06 17:54 UTC by seinnlee

Ticket [LF-2376](https://lite-farm.atlassian.net/browse/LF-2376)

**Description**
We want to notify a user when their task has been reassigned by assigner (i.e. farm owner or manager) to someone else.

**To Test:**
1. You will need at least one worker at your farm that you have access to.
2. Create a task and assign it to the worker from step 1.
3. Reassign the same task to someone else.
4. Log in to the account of the worker you initially assigned the task to from step 1.
5. You will see two notifications (initial assignment notification and reassignment notification)

I use the currently authenticated user's id as the assigner from request headers.

2022-05-06 22:40 UTC, Cali0707 approved these changes
I tested the functionality as described and it works as expected - both notifications showed up. This looks good to me.

2022-05-09 20:01 UTC, smattingly requested changes
Good work. I'd like to have a back-end Jest test for this. @seinnlee let me know if you need help with that. Also, if writing the test risks sprint tickets going unfinished, contact me and we can delay it by creating a tech debt ticket.

2022-05-09 20:57 UTC, seinnlee commented
> Good work. I'd like to have a back-end Jest test for this. @seinnlee let me know if you need help with that. Also, if writing the test risks sprint tickets going unfinished, contact me and we can delay it by creating a tech debt ticket.

@smattingly I'll need some help with writing tests. I've looked into it and it looks like the test will have to call both assignment endpoint and notification endpoint to test this functionality.

2022-05-19 19:02 UTC, Cali0707 approved these changes
One small change in a copyright comment should be made, bu otherwise this looks good to me!

2022-05-19 19:02 UTC, Cali0707 commented on packages/api/tests/taskNotification.test.js
> + *  Copyright 2019-2022 LiteFarm.org
```suggestion
 *  Copyright 2019, 2020, 2021, 2022 LiteFarm.org
```

2022-05-19 20:29 UTC, fsayyid approved these changes
Everything is working on my end and all tests are passing. @smattingly passing this off to you.

2022-05-20 01:21 UTC, smattingly approved these changes
Very good!

2022-05-23 19:55 UTC, merged