LF2230/allow completion of tasks for psuedo users
LiteFarmOrg/LiteFarm pull request #1886
Opened 2022-05-06 20:08 UTC by Cali0707

This PR adds functionality to complete tasks for pseudo users.

To test: 
1. Create a pseudo user on your farm by adding a user with no email
2. Assign a task to the pseudo user
3. Verify that for non admin accounts e.g. farm worker they do not have the option to complete the task for the pseudo user
4. Complete the task from an admin account (Farm Owner, Farm manager, extension officer)
5. Verify that the task is completed properly

2022-05-09 13:29 UTC, AbdusShaikh approved these changes
Working on both harvest and non-harvest tasks

2022-05-09 20:47 UTC, smattingly requested changes
Good work. Please see comments for a few needed changes (which led me to throw in some less critical suggestions, too.)

2022-05-09 20:47 UTC, smattingly commented on packages/api/src/controllers/taskController.js
> +      const { user_id } = req.headers;
Please use `req.user.user_id` instead of `req.headers.user_id`. Honestly, I'm just passing that along from past team members; I *suspect* I know why.

2022-05-09 20:47 UTC, smattingly commented on packages/api/src/controllers/taskController.js
> + * Checks if the current user can complete the task
JSDoc comments need a period at the end of this first description sentence. (I know that's very picky, but it's meaningful to the software that processes these, should we ever use it.)

2022-05-09 20:47 UTC, smattingly commented on packages/api/src/models/taskModel.js
> + *  GNU General Public License for more details, see <<https://www.gnu.org/licenses/>.>
Looks like extra angle brackets?

2022-05-09 20:47 UTC, smattingly commented on packages/api/src/models/taskModel.js
> +  static async getTaskAssignee(taskId) {
Thank you for putting this in the model. :+1:

2022-05-09 21:16 UTC, Cali0707 commented on packages/api/src/models/userFarmModel.js
> +  static async getUserRoleId(userId) {
I believe that in the case of `userFarmModel.js` we are extending the `Model` class from objection, not objection-soft-delete, so as far as I can tell we do not need it in this case. Also the queries seem to be returning the expected results. Should I update this model to extend `BaseModel` instead?

2022-05-10 14:41 UTC, Cali0707 commented
@smattingly I made the changes you requested and then rebased integration onto my branch to try and make merging easier. It looks like there are still some merge conflicts though.

2022-05-10 21:39 UTC, smattingly commented on packages/api/src/models/userFarmModel.js
> +  static async getUserRoleId(userId) {
You're right. I wonder why user and userFarm were not set up for soft delete? Anyway, I see no reason to change that now.

2022-05-10 21:40 UTC, smattingly approved these changes
Good work-- thanks.

2022-05-11 02:26 UTC, smattingly commented
> @smattingly I made the changes you requested and then rebased integration onto my branch to try and make merging easier. I haven't done a rebase before but it looks like this added many more changes to my PR than I intended. Is there a better way of fixing merge conflicts which I should be using going forwards?

@Cali0707 I usually merge rather than rebase. I know that the only difference between the two is how the history of commits is recorded; the resulting code contents are the same. You might try merge instead of rebase next time, but what you did is fine-- and appreciated.

2022-05-11 02:38 UTC, merged