Abandoned tasks now show abandonment date
LiteFarmOrg/LiteFarm pull request #1888
Opened 2022-05-09 13:01 UTC by AbdusShaikh

2022-05-09 13:08 UTC, AbdusShaikh commented
To test:
1. Create a task
2. Abandon this task ensuring the abandonment date is different from the due date
3. Confirm the abandonment is appearing in place of the due date in the Tasks page.

2022-05-09 18:50 UTC, seinnlee requested changes
If `trueDate` is only going to be passed into one component, I think it's better to write this mapping in `TaskCard.jsx` component rather than in `index.jsx` file.

2022-05-09 18:50 UTC, seinnlee commented on packages/webapp/src/containers/Task/TaskCard/index.jsx
> +  console.log(props);
I think you forgot to remove the console.log

2022-05-10 12:27 UTC, AbdusShaikh commented
> If `trueDate` is only going to be passed into one component, I think it's better to write this mapping in `TaskCard.jsx` component rather than in `index.jsx` file.

I have made a commit making these changes

2022-05-11 15:48 UTC, smattingly commented
@AbdusShaikh Since @seinnlee is out today, I will pick up the review of this from here.
Also, merge conflicts have developed for this branch. If you know how to address that, please do. If not, reach out and we can go through that.

2022-05-11 19:25 UTC, smattingly approved these changes
:+1:

2022-05-11 19:26 UTC, merged