Abandon rating, reason, and notes not showing on an abandoned crop plan detail page
LiteFarmOrg/LiteFarm pull request #1910
Opened 2022-05-16 18:47 UTC by jagDhillon077

Create 2 crop plans from any of the plants on the crop catalogue and complete one of the crop plans and abandon the other. Make sure to fill in the details of both the completed and abandoned crop plan such as abandon notes, reason for abandoning, completion notes, rating, etc. Once each of the crop plans have been completed you can then go on the details section of each and see that the completed crop plan does not show any abandonment details and the abandoned crop plan shows abandon details and reasoning.

2022-05-17 13:54 UTC, Cali0707 requested changes
@jagDhillon077 it looks like the "Reason for abandoning" field is not having its translations handled properly: 
![abandon_crop_plan_translation_error](https://user-images.githubusercontent.com/65566908/168827623-e022c5db-9a72-4183-89f1-ce5a244e2af5.png)
 Could you look into this?

2022-05-17 21:05 UTC, Cali0707 requested changes
@jagDhillon077 with the new changes, newly abandoned crop plans have the abandon reason displaying properly, but the one I already abandoned still has the same issue. Also, should we display "Date of status change" if there is no date of status change? Right now, it renders as "Invalid date"
![Date_of_status_change](https://user-images.githubusercontent.com/65566908/168909994-2fc2bcf1-a555-4715-bb03-5f0c6337311b.png)

2022-05-25 18:46 UTC, Cali0707 requested changes
@jagDhillon077 there is a new UI issue with these changes:
![managemnet_plan_complete_date_error](https://user-images.githubusercontent.com/65566908/170345237-9935ae06-77b1-4f27-8a65-98df92a7bd64.png)

2022-05-25 18:46 UTC, Cali0707 commented on packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx
> +      {console.log(plan)}
We should remove this console log

2022-05-25 19:24 UTC, Cali0707 approved these changes
Looks good to me

2022-05-26 14:57 UTC, smattingly approved these changes
:+1:

2022-05-26 14:57 UTC, merged