Feature/translations.fr/may.2022
LiteFarmOrg/LiteFarm pull request #1916
Opened 2022-05-17 21:11 UTC by slruder

These are my changes for French translation from today. I still have many to do. This is my first try at a pull request.

2022-05-19 00:50 UTC, smattingly reviewed
@slruder I marked one item that looks doubtful to me. Also, I wanted to confirm that we want to merge all those empty strings that replaced MISSING items.

2022-05-19 16:17 UTC, slruder commented on packages/webapp/public/locales/fr/common.json
> +  "MARK_COMPLETED": "Marquerpackages/webapp/public/locales/fr/common.json Complèté",
Thank you for catching that. I fixed it and will push through the change

2022-05-19 16:18 UTC, slruder commented on packages/webapp/public/locales/fr/common.json
> +  "MARK_COMPLETED": "Marquerpackages/webapp/public/locales/fr/common.json Complèté",
I am not sure what "merge all those empty strings that replaced MISSING items" means. Meeting with David to clarify.

2022-05-19 21:29 UTC, smattingly requested changes
@slruder @dtrapplitefarm I found a few things that I pointed out with review comments.

2022-05-19 21:29 UTC, smattingly commented on packages/api/src/templates/locales/fr.json
>      "HI": "EXPORT.HI",
I think the values in this block should have ordinary French text in them.

2022-05-19 21:29 UTC, smattingly commented on packages/webapp/public/locales/en/translation.json
> +    "NEED_MANAGEMENT_PLAN": "You'll need an active or planned crop plan before you can schedule a harvest task or transplant task. Go to the crop catalogue to create a plan now.",
I assume it's no problem, but I'll point out that the more exotic apostrophe characters that were in the files have been replaced with the mundane standard keyboard single quote. May have been done automatically by editor software.

2022-05-19 21:29 UTC, smattingly commented on packages/webapp/public/locales/fr/translation.json
> +    "DISABLE_GEO_LOCATION": "Les services de localisation doivent être activés pour trouver votre position actuelle",
There are three empty string values in this file.
(Nothing to do with this line; I can only put review comments on lines that were changed in the last update.)

2022-05-25 00:47 UTC, smattingly approved these changes

2022-05-25 00:47 UTC, merged