Augment user invitation page to specify the language their invitation account should be sent in
LiteFarmOrg/LiteFarm pull request #1925
Opened 2022-05-19 11:40 UTC by jagDhillon077

Click the top right icon and click 'my info' and navigate to the people tab and on the bottom it should have a button to invite a new user. When inviting a new user, you will see a new field 'Language of invitation' with a drop down with all 4 different languages a user can choose from.

2022-05-19 17:55 UTC, Cali0707 commented
@smattingly I've updated this ticket, so it should be ready to merge whenever it passes PR

2022-05-19 19:20 UTC, seinnlee approved these changes
LGTM. Tested for Spanish (worked) and French (didn't work but assumed that French translation for the email invitation is not in place yet?)

2022-05-19 19:20 UTC, seinnlee commented on packages/webapp/src/components/InviteUser/index.jsx
> +    console.log(data);
I think this was added for testing purpose. Seems a bit unnecessary to print a lot of data

2022-05-19 19:20 UTC, seinnlee commented on packages/webapp/src/containers/InviteUser/saga.js
> +  console.log(user);
Same here as well. Not sure if it's intended to be here.

2022-05-20 00:52 UTC, smattingly requested changes
Works well. I think it would be good to disable the new language input until an email address is provided.

2022-05-20 15:01 UTC, Cali0707 commented
@smattingly I've disabled the language input until an email is provided now - good call.

2022-05-25 14:27 UTC, Cali0707 commented
@smattingly I have fixed the merge conflicts

2022-05-26 14:55 UTC, smattingly approved these changes
:+1:

2022-05-26 14:55 UTC, merged