LF-2462 - feat: created notification timeline
LiteFarmOrg/LiteFarm pull request #2060
Opened 2022-06-09 21:02 UTC by fsayyid

Ticket: [LF-2462](https://lite-farm.atlassian.net/browse/LF-2462)

Created a notification timeline for viewing notifications related to the same entity (eg. a task).

To test:
- See [Figma](https://www.figma.com/file/F3f6DpGcxAaEsxfl7OZkI2/Litefarm?node-id=27547%3A88602&properties-panel-tab=code) for design expectations.
- Assign a task to yourself, then reassign/unassign it (we want to trigger two notifications);
- Go to the notification related to the above event, make sure that we see the notification timeline with the two notifications
- If you are viewing the "Assigned task" notification, make sure that the warning box shows up
- In the timeline, you should be able to click the different items to switch between related notifications

2022-06-10 14:58 UTC, Cali0707 approved these changes
Looks great!!

2022-06-13 18:40 UTC, smattingly requested changes
I'm impressed! This looks really good.
In the comments I had one question and one possible nitpicky change.
No changes necessary if the `location` key capitalization is intentional.

2022-06-13 18:40 UTC, smattingly commented on packages/webapp/src/components/Notifications/NotificationTimeline/index.jsx
> +          entityType={mostRecentNotification?.ref?.entity?.type}
I think the first optional chaining on this and the previous line are redundant with the check on lint 41?

2022-06-13 18:40 UTC, smattingly commented on packages/webapp/public/locales/en/translation.json
> +    "location": "location"
Is there a reason this key name is in lower case? It seems inconsistent, possibly incorrect (I know sometimes strings are converted to upper case for uses like these).

2022-06-14 14:25 UTC, smattingly approved these changes

2022-06-14 14:26 UTC, merged