LF-2478 conversion of pseudo user to use the existing user's language preference
LiteFarmOrg/LiteFarm pull request #2114
Opened 2022-06-30 22:20 UTC by seinnlee

This PR addresses the comment to this ticket [LF-2478](https://lite-farm.atlassian.net/browse/LF-2478)

To Test:
1. Create a user account (in a different language than English)
2. Log into a farm that you already have and create a pseudo user
3. Convert that pseudo user to a user with an account but invite the user from step 1 (select English or a language different from step 1 as the language of invitation)
4. The invite email language should be that of the invitation language (step 3), but upon clicking the invite link, the app should be in the user's language preference from step 1

2022-07-06 13:47 UTC, AbdusShaikh approved these changes
Tried with several different languages and accounts and they all behaved correctly.

2022-07-06 14:36 UTC, smattingly commented
@seinnlee As I read them, your description of expected behavior above does not match description in the Jira comment. I'll raise that in discussion on the ticket.

2022-07-06 18:12 UTC, smattingly requested changes
See earlier comment.

2022-07-07 20:38 UTC, smattingly approved these changes

2022-07-07 20:38 UTC, merged