Added multi-langauge support for bulk sensor upload
LiteFarmOrg/LiteFarm pull request #2167
Opened 2022-07-19 21:31 UTC by anant00729

To test, 

Please check, https://lite-farm.atlassian.net/browse/LF-2659

2022-07-20 14:54 UTC, dtrapplitefarm approved these changes

2022-07-20 19:36 UTC, Cali0707 requested changes

2022-07-20 19:36 UTC, Cali0707 commented on packages/webapp/public/locales/fr/translation.json
> +        "TEMPERATURE": "temperatura"
Should be 'température'

2022-07-20 20:10 UTC, anant00729 commented on packages/webapp/public/locales/fr/translation.json
> +        "TEMPERATURE": "temperatura"
Done

2022-07-21 17:44 UTC, Cali0707 approved these changes
Looks good, thanks for fixing that translation @anant00729 !

2022-07-21 17:45 UTC, Cali0707 commented
@anant00729 can you fix the merge conflict on this PR?

2022-07-21 18:30 UTC, smattingly approved these changes

2022-07-21 18:30 UTC, merged