Lf 2669-after retiring a sensor it isnt immediately removed from the farm map
LiteFarmOrg/LiteFarm pull request #2195
Opened 2022-07-26 17:32 UTC by AbdusShaikh

To test:
1. Upload a sensor if you don't already have on
2. Click on it in the map and retire it

You should see a success message snackbar and the sensor should no longer appear on the map

2022-07-26 17:42 UTC, fsayyid commented on packages/api/src/controllers/sensorController.js
> +      const { external_id, location_id, farm_id, partner_id, brand_name } = req.body;
Client should have to send this data in the request body. Just the `location_id` should be enough to unclaim the sensor.

2022-07-26 17:45 UTC, fsayyid commented on packages/api/src/controllers/sensorController.js
> +      const { external_id, location_id, farm_id, partner_id, brand_name } = req.body;
You can pull the other data from the database.

2022-08-02 13:45 UTC, fsayyid approved these changes
This seems to be working in the non-esci sensor case. And I have a PR to fix the retiring an ESCI sensor bug.

2022-08-02 13:45 UTC, fsayyid commented
Please deal with the merge conflicts

2022-08-03 15:06 UTC, Cali0707 requested changes
@AbdusShaikh I'm getting an error: `Uncaught ReferenceError: DEPTH_UNIT is not defined`

2022-08-04 17:40 UTC, Cali0707 requested changes
@AbdusShaikh when I try and retire an ESCI sensor nothing happens - seems to be working for non ESCI sensors though

2022-08-04 17:58 UTC, AbdusShaikh commented
> @AbdusShaikh when I try and retire an ESCI sensor nothing happens - seems to be working for non ESCI sensors though

This issue was addressed by a seperate PR: [#2198](https://github.com/LiteFarmOrg/LiteFarm/pull/2198)

2022-08-04 18:18 UTC, fsayyid commented
@AbdusShaikh need to merge integration into your branch

2022-08-05 16:21 UTC, Cali0707 approved these changes
This is working for me!

2022-08-05 16:33 UTC, merged