Fixed 400 error when updating sensor
LiteFarmOrg/LiteFarm pull request #2202
Opened 2022-07-27 16:38 UTC by jagDhillon077

To test:

Drop database and recreate with new updated sensor migrations

Upload a sensor 
Update the sensor values
Ensure the sensor successfully updates and doesn't throw a 400 (bad request) error

2022-07-27 17:38 UTC, AbdusShaikh requested changes
Tested by updating name, lat/lng, reading types, and depth. All are working except depth

2022-07-28 17:45 UTC, anant00729 commented
Tested the update flow: name, lat, long, and depth are getting updated on my end.

Step: 1: Before Update
<img width="565" alt="Screen Shot 2022-07-28 at 10 41 47 AM" src="https://user-images.githubusercontent.com/20675885/181603262-1d648c14-ccbc-4015-9fa9-945d83e47a61.png">

Step 2: On Update
<img width="581" alt="Screen Shot 2022-07-28 at 10 42 16 AM" src="https://user-images.githubusercontent.com/20675885/181603074-1fa55280-8f68-4416-a9f8-8cc0156e6737.png">

Step 3: After Update
<img width="581" alt="Screen Shot 2022-07-28 at 10 42 28 AM" src="https://user-images.githubusercontent.com/20675885/181603139-7ea9edcb-fc02-4bb7-a3fb-c3ddd88e2372.png">

2022-07-28 17:46 UTC, anant00729 approved these changes

2022-07-29 20:46 UTC, fsayyid commented
I'm not sure if editing existing migration is the best approach since these migrations have already been run on beta. We could do it this way, but we would also need an sql script or a knex migration that we can run on the beta database to make these changes.

2022-08-02 17:24 UTC, closed without merging