LF-2253 when revoking a users access ensure at least one fo fm or eo retains access to the farm
LiteFarmOrg/LiteFarm pull request #2220
Opened 2022-08-04 21:06 UTC by seinnlee

Ticket [LF-2253](https://lite-farm.atlassian.net/browse/LF-2253)

To Test:
1. Create a farm with one admin account (try one admin and no workers, try one inactive admin and one active admin, try two active admins, etc.).
2. Go edit the last admin's profile.
3. Click "Revoke User Access".
4. "Cannot revoke access" modal should pop up instead of "Revoke User Access" modal.
5. If you click "here" in the modal, it should redirect you to Request Help page.

2022-08-05 16:29 UTC, Cali0707 requested changes
@seinnlee if I invite a second manager from the people tab and then try to revoke access to either the second manager or my current user, it says that I can't revoke access for the last admin on the farm. This probably shouldn't happen, because as I understand it there would be two admins on the farm in this scenario

2022-08-05 18:13 UTC, seinnlee commented
@Cali0707 I updated it so that you can revoke invited managers as long as there is an active admin. But I don't think you should be able to revoke access of yourself when the invited manager hasn't created an account yet (they could have made a typo in the invite email, etc.).

2022-08-08 15:25 UTC, Cali0707 approved these changes
This looks good to me!

2022-08-08 20:01 UTC, fsayyid approved these changes

2022-08-08 20:02 UTC, merged