Made retired sensors show up when re uploaded
LiteFarmOrg/LiteFarm pull request #2227
Opened 2022-08-08 15:08 UTC by Cali0707

This PR resolves the issues reported by Mwaya on https://lite-farm.atlassian.net/browse/LF-2672 

To test:
1. Retire a sensors on a farm
2. Re upload that same sensor
3. The sensor should show up on your map without you needing to refresh

2022-08-08 17:17 UTC, AbdusShaikh approved these changes
Works as expected

2022-08-08 22:16 UTC, fsayyid requested changes
The sensor reupload sucessfully, but it doesn't show up in the UI immediately like it does when you upload it for the first time.

2022-08-09 14:12 UTC, Cali0707 commented
@fsayyid this is the behaviour I'm seeing:

https://user-images.githubusercontent.com/65566908/183671269-493cc072-6699-416a-90f7-a0faf5c314cf.mov

Are you running the latest version of this branch?

2022-08-09 14:21 UTC, fsayyid approved these changes

2022-08-09 14:21 UTC, merged