Lf 2803 irrigation post
LiteFarmOrg/LiteFarm pull request #2352
Opened 2022-12-01 20:16 UTC by wasswarichard

https://lite-farm.atlassian.net/browse/LF-2803

2022-12-02 02:49 UTC, Duncan-Brain commented
@wasswarichard 

Here's what I got so far without testing it...
1. taskController - looks like its going to interfere with @anant00729 LF-2818 maybe wait or coordinate with him after that is merged before this PR
2. TaskLocations/index - looks like you accidentally mixed this up from a different branch! This is from my most recent PR and doesnt belong here

2022-12-03 03:48 UTC, JimmyRowland commented on packages/api/src/controllers/taskController.js
> +  async checkCustomDependencies(typeOfTask, data, farm_id) {
use withGraphFetched
https://vincit.github.io/objection.js/api/query-builder/eager-methods.html

2022-12-03 03:55 UTC, JimmyRowland commented on packages/api/src/controllers/taskController.js
> +  async checkCustomDependencies(typeOfTask, data, farm_id) {
https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#upsertgraph
Documentation for upsert graph. These are already implemented by objection js. Just add proper relation mappings to task models and validations

2022-12-05 15:11 UTC, wasswarichard commented
@anant00729 please look at this

2022-12-05 17:14 UTC, anant00729 requested changes

2022-12-05 17:14 UTC, anant00729 commented on packages/api/src/controllers/taskController.js
> +          await IrrigationTypesModel.query()
can shift this line to IrrigationTypesModel file. can add this in the static function.

2022-12-05 17:14 UTC, anant00729 commented on packages/api/src/controllers/taskController.js
> +            await locationDefaultsModel.transaction(async (trx) => {
can shift this line to LocationDefaultsModel file. can add this in the static function.

2022-12-05 17:14 UTC, anant00729 commented on packages/api/src/models/irrigationTypesModel.js
> +    const irrigation_type_names = await knex('irrigation_type').select('irrigation_type_name');
use camel case e.g IrrigationTypeNames

2022-12-05 21:41 UTC, anant00729 commented
Looks good to me

2022-12-05 21:42 UTC, anant00729 approved these changes

2022-12-05 21:42 UTC, merged