LF-2851 Biodiversity text now displays Click to calculate
LiteFarmOrg/LiteFarm pull request #2418
Opened 2023-01-17 23:22 UTC by craigyu

[Jira ticket 2851](https://lite-farm.atlassian.net/browse/LF-2851)

I commented out the code that fetches and displays biodiversity data in the file, in case we need to use it in the future.
Sorry about the 2 useless commits, I was having git issues and those were for testing my GitHub access.

2023-01-18 16:53 UTC, Duncan-Brain requested changes
Gosh what a mess this file is! Thanks for doing some housekeeping.

It works as expected for me.

But I think you can just delete all the commented out code. I think there are even a few more constants and useless vars that can go.

2023-01-18 21:44 UTC, craigyu commented
> Gosh what a mess this file is! Thanks for doing some housekeeping.
> 
> It works as expected for me.
> 
> But I think you can just delete all the commented out code. I think there are even a few more constants and useless vars that can go.

@Duncan-Brain Done!

2023-01-19 01:09 UTC, kcussen commented
@SayakaOno can you take a look to familiarize yourself with the biodiversity insight? We've got a ticket in the Spring release to overhaul this, so now's a good time to take a peek =) 

I'll merge if you approve.

2023-01-19 17:32 UTC, SayakaOno approved these changes

2023-01-19 17:39 UTC, merged