LF-2813-Resolve-all-medium-and-low-dependabot-alerts-15
LiteFarmOrg/LiteFarm pull request #2532
Opened 2023-03-30 20:39 UTC by liao02x

**Description**

Resolving the moderate and low alerts. `request` is deprecated so the alerts around it are not resolved. Renamed pnpm lock file so it's easier to tell pnpm is not used.

Jira link: https://lite-farm.atlassian.net/browse/LF-2813

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

It only affects lerna and the packages in `packages/api`. The `npm run test` passed on api.

- [x] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

2023-04-04 23:10 UTC, SayakaOno approved these changes

2023-04-07 10:13 UTC, mickenorlen requested changes
Hi, I think I made a mistake in my review. I'll try again

2023-04-07 12:16 UTC, mickenorlen approved these changes
Thank you for your work on this one. Everything seems to be working well!

What I tested:

- Wipe db
- Install new deps
- Run migrations
- Wipe browser data or enter app incognito, create new farm etc
- Click around in most places I know. Try to create a couple of things
- Compare any console errors to beta

2023-04-07 22:39 UTC, Duncan-Brain approved these changes
Thanks for this, it looks like this fix was added to the high alerts ticket as well at your suggestion.

2023-04-07 22:43 UTC, SayakaOno approved these changes

2023-04-07 22:43 UTC, merged