LF-3332: Fix npm vulnerable packages
LiteFarmOrg/LiteFarm pull request #2730
Opened 2023-06-15 00:05 UTC by SayakaOno

**Description**

### webapp
- fix packages by running `pnpm audit --fix`
- uninstall `xlsx`

- there is [one remaining issue](https://github.com/advisories/GHSA-353f-5xf4-qw67), but our app doesn't seem to be affected.
  > Only users explicitly exposing the Vite dev server to the network (using --host or [server.host config option](https://vitejs.dev/config/server-options.html#server-host)) are affected, and only files in the immediate Vite project root folder could be exposed.

### api
- `npm audit fix`
- update `jwks-rsa`
- update `express-jwt`. (most of the changes in this PR are related to this) README: [Migration from v6](https://github.com/auth0/express-jwt#migration-from-v6)
  - `req.user` -> `req.auth`
  - `import jwt from ...` -> `import { expressjwt } from ...`
- [override](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) `glob-parent`. There is a [bug](https://github.com/npm/cli/issues/5443) that `overrides` does not work after running `npm install`. `npm update` needs to be run to make the `overrides` work.
- there are two remaining issues.
  - `dicer` - No fix available
  <img width="596" alt="Screenshot 2023-06-14 at 4 59 54 PM" src="https://github.com/LiteFarmOrg/LiteFarm/assets/33141219/5dfc066b-0351-4d31-9a0e-4bd4d632824e">
  
  - `request` - [deprecated](https://www.npmjs.com/package/request)
  <img width="651" alt="Screenshot 2023-06-14 at 5 01 04 PM" src="https://github.com/LiteFarmOrg/LiteFarm/assets/33141219/d658032e-6591-4f3f-b4de-9a9ee6bc025c">

Jira link: https://lite-farm.atlassian.net/browse/LF-3332

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

2023-06-15 19:38 UTC, kathyavini commented
@SayakaOno thanks for the heads up! It looks like `xlsx` was refactored out of the sensor validation flow quite a while ago so it's all good 👍

2023-06-15 19:58 UTC, SayakaOno commented
@kathyavini thank you so much for confirming!

2023-06-16 12:15 UTC, iperdomo requested changes
Minor comments around modifying commented code. We have the git history. Let's remove the commented out code.

2023-06-16 12:15 UTC, iperdomo commented on packages/api/src/controllers/baseController.js
> +//     return await model.query(trx).context({ user_id: req?.auth?.user_id, ...context }).insert(data);
@SayakaOno can we please remove all this commented out code? I think is misleading

2023-06-16 12:15 UTC, iperdomo commented on packages/api/tests/crop.test.js
> +    //   req.auth.user_id = req.get('user_id');
🗑️ away

2023-06-16 19:38 UTC, Duncan-Brain commented
Hallo!

Webapp
- Vite --host  --> we actually may expose this in our cypress tests github action we run pnpm dev on CI It would probably be good to update vite on another ticket.

Api
 - jwks-rsa --> can we just remove this? I do not see it used anywhere
 - override glob parent --> am I right in reading that once we update npm (node) this can be removed?
 - dicer --> I am not seeing the offending package on the newest lts for multer. Would adding a ticket to upgrade multer maybe fix it?

2023-06-17 10:32 UTC, iperdomo approved these changes

2023-06-19 16:49 UTC, merged