LF-3387 Add --inspect to API run script to attach debugger
LiteFarmOrg/LiteFarm pull request #2732
Opened 2023-06-15 20:59 UTC by kathyavini

**Description**

This PR provides an alternative `npm run nodemon` script (`npm run debug`) which is equivalent except it provides a port for attaching a Node.js debugger.

The VS Code Run and Debug configuration that goes with this (thank you @mickenorlen for the example and the annotations!!) is as follows. If you aren't running the API inside a Docker container, the `remoteRoot` is unnecessary:

```json
{
  "version": "0.2.0",  "configurations": [
    {
      "name": "api",
      // Type of application to attach to
      "type": "node",
      // Type of request
      "request": "attach",
      // Restart on disconnection
      "restart": true,
      // Docker bound inspect/debug port
      "port": 9230,
      // Host system path to api root
      "localRoot": "/home/micke/Code/LiteFarm/packages/api",
      // Docker container api root
      "remoteRoot": "/usr/src/app"
    },
  ]
}
```

For instance, I use the following configurations with the Dockerized export server (PR https://github.com/LiteFarmOrg/LiteFarm/pull/2728) and a non-containzerized API:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "API: Attach to Node",
      "port": 9230,
      "restart": true,
      "address": "localhost",
      "localRoot": "${workspaceFolder}"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Docker Export Server: Attach to Node",
      "port": 9229,
      "restart": true,
      "address": "localhost",
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/api"
    }
  ]
}
```

Jira link: https://lite-farm.atlassian.net/browse/LF-3387

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [x] Other (please explain)

Add the configuration to the VS Code Run & Debug > Add Configuration. After starting the backend with `npm run debug` you can run the configuration to attach to the running process. If you are using Docker make sure that the debug port is exposed to the host system.

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

2023-06-16 09:40 UTC, iperdomo requested changes
Let's consider adding `--inspect` to `nodemon` script.

2023-06-16 20:29 UTC, Duncan-Brain commented
Very cool! And thanks to @mickenorlen !

Your config here works well for me -- VS code default debugger is pretty buggy ironically.

I will try to incorporate debugger into my testing now.

2023-06-16 20:29 UTC, Duncan-Brain approved these changes

2023-06-17 10:07 UTC, iperdomo approved these changes
LGTM 👍🏾

2023-06-17 10:07 UTC, merged