Lf 3361 repeat crop plan modify name crop plan screen
LiteFarmOrg/LiteFarm pull request #2768
Opened 2023-07-14 22:19 UTC by gursimran-singh

**Description**

This PR adds option to select the crop plan for repeat. if "This crop plan repeats" option is selected then if should be redirected to `/repeat` after save else to `/tasks` along with other required URL params.

Jira link:https://lite-farm.atlassian.net/browse/LF-3361

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**
Create a crop plan as normal, and on the name crop plan screen you will find the option "This crop plan repeats" to select this plan for repeat. if selected it should be redirected to `/repeat` along with other required params else to `/tasks`. As of now after selecting the crop plan for repeat, it takes you to home screen after save because its functionality is being worked in this ticket https://lite-farm.atlassian.net/browse/LF-3362.

- [x] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [x] I have added or updated language tags for text that's part of the UI
- [x] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

2023-07-17 16:24 UTC, iperdomo requested changes
Hi @gursimran-singh thanks for your PR. Apologies for the late reply.

With the most recent changes in `integration` there are some conflicts in translation files and one jsx file. Can you update your branch with the most recent changes from `integration`? Thanks,

2023-07-17 18:35 UTC, gursimran-singh commented
@iperdomo Done, updated with latest code.

2023-07-19 16:47 UTC, kathyavini approved these changes
Thank you Gursimran. It looks great and the pathing is perfect! 👌

2023-07-19 17:10 UTC, iperdomo approved these changes

2023-07-19 17:10 UTC, merged