[WIP] LF-4251: Add more inputs to AddSoilAmendmentProducts component
LiteFarmOrg/LiteFarm pull request #3241
Opened 2024-06-19 23:16 UTC by SayakaOno

**Description**
-

Jira link: https://lite-farm.atlassian.net/browse/LF-4251

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

2024-07-02 19:38 UTC, Duncan-Brain requested changes
Looking great overall!

EDITED: NEVERMIND the request changes I think I did the same thing as before with 1:1 vs percent and thinking it was not working lol

I also thought at first it was not possible to "clear" moisture content percent back to undefined/null values but instead of using backspace I used delete and it was ok.

2024-07-02 19:39 UTC, Duncan-Brain approved these changes

2024-07-05 19:27 UTC, SayakaOno commented
Thank you @Duncan-Brain for reviewing!
The moisture content percent input seems to be working fine for me with both backspace and delete, but I will keep an eye on it!

I noticed that I forgot to add options for `molecular_compounds_unit`... I will add it to this PR, sorry 🙏

2024-07-08 23:10 UTC, kathyavini approved these changes
Okay the form has gotten rather long + complicated but this looks really good!

I think I do mostly follow the form logic now and the relationship between the two... I think the `<QuantityApplicationRate />` will need to call `useFormContext()` as you mentioned on that PR, and also have the `namePrefix` applied, correct? It shouldn't be too bad then, I think.

2024-07-08 23:10 UTC, kathyavini commented on packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/index.tsx
> +            validate: (value) => {
Using this + the form `isValid` state is indeed quite improved (simplified) from `getInvalidProductsUpdater` 🙂  I like it!

2024-07-09 13:51 UTC, Duncan-Brain approved these changes
Looks amazing! A flakey test failed on cropVariety tests so I re-ran the test.

2024-07-09 13:51 UTC, merged

2024-07-09 15:23 UTC, SayakaOno commented
@kathyavini Thank you for reviewing!
Yes, that's correct! `useFormContext()` + `namePrefix` should add the form values to the right place!