LF-4348 Demo branch -- Pass other_purpose_id as a form field
LiteFarmOrg/LiteFarm pull request #3339
Opened 2024-07-24 21:47 UTC by kathyavini

**Description**

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Jira link:

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

2024-07-24 21:50 UTC, SayakaOno approved these changes
Looks good to me!

2024-07-25 15:26 UTC, Duncan-Brain commented on packages/webapp/src/util/task.ts
> +    return { purpose_id, other_purpose: purpose_id == otherPurposeId ? otherPurpose : undefined };
@kathyavini 

I am seeing the other_purpose I specify not make it to the database. Is it possible one of these is a string and not the other?

2024-07-25 15:26 UTC, Duncan-Brain requested changes
This one is pretty easy to understand which I like and was my first instinct -- but I have yet to figure out if we want to use Sayaka's method in the future for working with rtkquery. 

I think its not yet working tho left an inline comment

2024-07-25 16:01 UTC, Duncan-Brain approved these changes

2024-07-25 16:28 UTC, merged