Lf 4414 the user is able to create an animal with the incomplete date of birth or date brought in
LiteFarmOrg/LiteFarm pull request #3473
Opened 2024-09-23 17:09 UTC by dariaedicas

**Description**

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Jira link:
https://lite-farm.atlassian.net/browse/LF-4414
**Type of change**
 Bug fix 
**How Has This Been Tested?**
UI components visually reviewed on desktop view

2024-09-23 21:42 UTC, antsgar approved these changes
Solution looks good and seems to be working properly, thank you for contributing @dariaedicas! 🚀 I didn't know `onChange` didn't fire for keyboard input on a date field, it's cool to learn that (although inconvenient in this case).

My only suggestion for next time would be to add the context that you commented in the Jira ticket in the PR description as well, it helps reviewers get a notion on the reasoning behind the change and makes reviews easier.

2024-09-23 21:42 UTC, antsgar commented on packages/webapp/src/components/Animals/DetailCards/Origin.tsx
> +        onKeyUp={(e: any) => {
Not a blocker for merge but if we could annotate these functions properly like so

```suggestion
        onKeyUp={(e: React.ChangeEvent<HTMLInputElement>): void => {
```

it'd be great!

2024-09-23 22:40 UTC, Duncan-Brain requested changes
Cool change ! I never heard of e.target.validity.badInput before!

Only issue for me is technically `moment` is deprecated and we prefer not to use it in new code if possible. If too challenging to replace that specific function with a regular Date function I can approve.

2024-09-24 17:32 UTC, Duncan-Brain commented on packages/webapp/src/components/Animals/DetailCards/Origin.tsx
> +import { isNotInFuture, parseISOStringToLocalDate } from '../../Form/Input/utils';
Looks like parseISO.. is unused.

2024-09-24 17:35 UTC, Duncan-Brain reviewed
That was fast, I am happy that there was something around plain Date that worked out!

Just made one small inline comment.

2024-09-25 14:31 UTC, antsgar approved these changes

2024-09-26 18:22 UTC, Duncan-Brain approved these changes

2024-09-26 18:22 UTC, merged