New Crowdin translations webapp_consent
LiteFarmOrg/LiteFarm pull request #3577
Opened 2024-12-06 03:39 UTC by LiteFarm-eng

New Crowdin pull request with translations of webapp_consent

2024-12-06 03:45 UTC, kathyavini commented
Please ignore but keep open so we don't keep regenerating it with each pull 🙏

2024-12-06 03:46 UTC, kathyavini requested changes
Please ignore but keep open so we don't keep regenerating it with each pull 🙏

2025-01-13 19:09 UTC, kathyavini approved these changes
@Duncan-Brain and @SayakaOno I did the following to the CrowdIn pull:

1. Removed Polish
2. Restored the integration version of `es`/`en`/`fr`/`pt` since that is what we had approved
3. Fixed a redundant line in English that Larisse spotted

**However, because I did #2 and #3 with my pre-commit linter active, it fixed the markdown trailing spaces.** I'm okay with this, but if you can think of a reason it's not a good idea (I guess it would change the last edited date if that's a property we care about 🤔 ), I will disable my pre-commit and redo.

Edit: Blech I see the CrowdIn bot also did something very annoying with the redundant "for further information" line (inserted in in English into the other files); will fix that!

2025-01-13 19:19 UTC, SayakaOno commented on packages/webapp/src/containers/Consent/locales/de/Owner.Consent.md
> +- •	Angaben zum Tier: Name des einzelnen Tieres oder der Tiergruppe, Art, Rasse, Geschlecht, Einbringungs- oder Geburtsdatum und andere Angaben zur Identifizierung.
Should we remove the bullet point or is it fine...?
I'm okay with everything else too!

2025-01-13 19:23 UTC, kathyavini commented on packages/webapp/src/containers/Consent/locales/de/Owner.Consent.md
> +- •	Angaben zum Tier: Name des einzelnen Tieres oder der Tiergruppe, Art, Rasse, Geschlecht, Einbringungs- oder Geburtsdatum und andere Angaben zur Identifizierung.
Thank you! Yes, let's remove it. I think we have license to fix up formatting as needed 🙂

2025-01-14 17:35 UTC, SayakaOno approved these changes

2025-01-14 17:36 UTC, Duncan-Brain approved these changes

2025-01-14 17:37 UTC, merged