Lf 935/enter area details
LiteFarmOrg/LiteFarm pull request #666
Opened 2021-03-10 21:09 UTC by kaavyalakshmanan

2021-03-15 22:10 UTC, beetai requested changes
Something that are not addressed in comments linked to code:
- Is the "successfully added" message within the scope of the task? If so, will this be addressed after this has been merged?

2021-03-15 22:22 UTC, kikemarquez8 commented on packages/webapp/src/stories/AreaDetails/AreaDetails.stories.js
> +  areaType: (data) => console.log(data),
agree

2021-03-15 22:23 UTC, kikemarquez8 commented on packages/webapp/src/index.js
> +import farmSiteBoundaryLocationSaga from './containers/AreaDetailsLayout/FarmSiteBoundary/saga';
I could go either way with this

2021-03-15 22:28 UTC, kaavyalakshmanan commented on packages/webapp/src/Routes.js
> +const WaterValve = React.lazy(() => import('./containers/PointDetailsLayout/WaterValve'));
Doe

2021-03-15 22:34 UTC, kaavyalakshmanan commented on packages/webapp/src/stories/TitleLayout/TitleLayout.stories.js
> +};
Done.

2021-03-15 22:36 UTC, kaavyalakshmanan commented on packages/webapp/src/stories/AreaDetails/AreaDetails.stories.js
> +  areaType: (data) => console.log(data),
Done.

2021-03-15 22:39 UTC, kaavyalakshmanan commented on packages/webapp/src/index.js
> +import farmSiteBoundaryLocationSaga from './containers/AreaDetailsLayout/FarmSiteBoundary/saga';
Done.

2021-03-15 22:44 UTC, kaavyalakshmanan commented on packages/webapp/src/containers/PointDetailsLayout/Gate/saga.js
> +      locationURL + '/' + `${locationObject.figure.type}`,
Done.

2021-03-15 22:56 UTC, kaavyalakshmanan commented on packages/webapp/src/containers/PointDetailsLayout/WaterValve/index.js
> +    resetLocationData();
Done.

2021-03-15 22:57 UTC, kaavyalakshmanan commented on packages/webapp/src/containers/Map/useMapAssetRenderer.js
> +    // }
This is commented out because according to Jimmy, the line function hasn't been completed yet. Guessing it will be uncommented in the next sprint.

2021-03-15 23:43 UTC, kaavyalakshmanan commented on packages/webapp/src/components/PointDetailsLayout/index.js
> +          </Button>
Done.

2021-03-16 00:11 UTC, kikemarquez8 approved these changes

2021-03-16 00:14 UTC, merged